# Generated by Django 4.0.5 on 2022-06-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='organization',
            new_name='organization_name',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='email_verified',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='address',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='city',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='country',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='organization_cin',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='organization_gstin',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='state',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='verifying_token',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
