# Generated by Django 4.0.5 on 2022-06-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_userprofileinfo_verifying_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='verifying_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
