# Generated by Django 4.0.5 on 2022-06-20 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_userprofileinfo_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='email_verified',
        ),
    ]
