# Generated by Django 4.0.5 on 2022-06-23 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0006_remove_userprofileinfo_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='documents_uploaded',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='verifying_token',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_of_identity', models.FileField(upload_to='files/')),
                ('proof_of_address', models.FileField(upload_to='files/')),
                ('proof_of_gst', models.FileField(upload_to='files/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
