# Generated by Django 4.0.5 on 2022-06-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_catalogue_starting_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='starting_bid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
