# Generated by Django 4.0.5 on 2022-06-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_cataloguefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='strategy',
            field=models.CharField(choices=[('ascending', 'low to high'), ('descending', 'high to low'), ('quotes', 'get quotation')], default='ascending', max_length=10),
            preserve_default=False,
        ),
    ]
