# Generated by Django 4.0.5 on 2022-07-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_catalogue_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='broker_fees',
            field=models.FloatField(default=0),
        ),
    ]
