# Generated by Django 4.0.5 on 2022-07-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_catalogue_broker_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='tech_specs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
