# Generated by Django 4.0.5 on 2022-07-11 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_bid_tech_specs'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='slug',
            field=models.SlugField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.catalogue'), unique=True),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='starting_bid',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
