# Generated by Django 4.0.5 on 2022-07-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_bid_slug_alter_catalogue_starting_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
