# Generated by Django 4.0.5 on 2022-07-11 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_alter_bid_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='slug',
        ),
    ]
