# Generated by Django 4.0.5 on 2022-07-01 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0005_catalogue_strategy'),
        ('registration', '0007_userprofileinfo_documents_uploaded_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(default='Pending', max_length=100)),
                ('order_id', models.CharField(max_length=100)),
                ('payment_id', models.CharField(max_length=100)),
                ('signature_id', models.CharField(max_length=100)),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.catalogue')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.userprofileinfo')),
            ],
        ),
    ]
