# Generated by Django 4.0.5 on 2022-07-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fee_amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
